export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";

export const FETCH_POKEMON_FAILURE = "FETCH_POKEMON_FAILURE";

export const FETCH_POKEMON_REQUESTED = "FETCH_POKEMON_REQUESTED";

export const FETCH_POKEMON_DETAILS_SUCCESS = "FETCH_POKEMON_DETAILS_SUCCESS";

export const FETCH_POKEMON_DETAILS_FAILURE = "FETCH_POKEMON_DETAILS_FAILURE";

export const FETCH_POKEMON_DETAILS_REQUESTED = "FETCH_POKEMON_DETAILS_REQUESTED";

export const FETCH_SPECIES_DETAILS_SUCCESS = "FETCH_SPECIES_DETAILS_SUCCESS";

export const FETCH_SPECIES_DETAILS_FAILURE = "FETCH_SPECIES_DETAILS_FAILURE";

export const FETCH_SPECIES_DETAILS_REQUESTED = "FETCH_SPECIES_DETAILS_REQUESTED";

export const SEARCH_POKEMON_BY_NAME = "SEARCH_POKEMON_BY_NAME";